services:
  mysql:
    image: mysql:8.0
    container_name: mysql_laravel_tasks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: laravel_tasks
      MYSQL_USER: anderson_dev
      MYSQL_PASSWORD: StrongPass123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: